// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQoxyUKAUsSuF25WxNOBMUcYmxd3WMqE',
    appId: '1:382856269132:web:8e1bdb219a6a03c4f253e9',
    messagingSenderId: '382856269132',
    projectId: 'myrecipediary-7365a',
    authDomain: 'myrecipediary-7365a.firebaseapp.com',
    storageBucket: 'myrecipediary-7365a.appspot.com',
    measurementId: 'G-6TWZ4BL7JM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsD52A6HEpXrzGtsinvw18qJUkro5wGEU',
    appId: '1:382856269132:android:7695e1da51531bf7f253e9',
    messagingSenderId: '382856269132',
    projectId: 'myrecipediary-7365a',
    storageBucket: 'myrecipediary-7365a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIV9hB5e5SObDZEOcRp11umUZJ__-qbs',
    appId: '1:382856269132:ios:b09b5768dbd0cff5f253e9',
    messagingSenderId: '382856269132',
    projectId: 'myrecipediary-7365a',
    storageBucket: 'myrecipediary-7365a.appspot.com',
    iosBundleId: 'com.example.myrecipediary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIV9hB5e5SObDZEOcRp11umUZJ__-qbs',
    appId: '1:382856269132:ios:b09b5768dbd0cff5f253e9',
    messagingSenderId: '382856269132',
    projectId: 'myrecipediary-7365a',
    storageBucket: 'myrecipediary-7365a.appspot.com',
    iosBundleId: 'com.example.myrecipediary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyQoxyUKAUsSuF25WxNOBMUcYmxd3WMqE',
    appId: '1:382856269132:web:a284ec4aa725197cf253e9',
    messagingSenderId: '382856269132',
    projectId: 'myrecipediary-7365a',
    authDomain: 'myrecipediary-7365a.firebaseapp.com',
    storageBucket: 'myrecipediary-7365a.appspot.com',
    measurementId: 'G-E5BELHEZPS',
  );
}
